In [184]:
def add_list(size_of_list):
    l1 = list(range(size_of_list))
    l2 = list(range(size_of_list))
    l = [l1[i] + l2[i] for i in range(size_of_list)]
    return l

# Numpy

#### Motivation For Numpy

In [185]:
def add_list(size_of_list):
    l1 = list(range(size_of_list))
    l2 = list(range(size_of_list))
    l = [l1[i] + l2[i] for i in range(size_of_list)]
    return l

In [186]:
size = 10000000

In [187]:
%%time
add_list(size)[0:10]

CPU times: total: 5.56 s
Wall time: 5.76 s


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [188]:
import numpy as np

In [189]:
def add_ndarray(size_of_array):
    l1 = np.arange(size_of_array)
    l2 = np.arange(size_of_array)
    return l1 + l2

In [190]:
%%time
add_ndarray(size)[:10]

CPU times: total: 62.5 ms
Wall time: 77.8 ms


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

####  NumPy ndarrays

In [191]:
import numpy as np

In [192]:
arr = np.array([0, 1, 1, 2, 3, 5])
print(arr)

[0 1 1 2 3 5]


In [193]:
arr2d = np.array([ [0, 1, 1], 
                   [2, 3, 5] ])
print(arr2d)

[[0 1 1]
 [2 3 5]]


In [194]:
print(arr.ndim)
print(arr.shape)

1
(6,)


In [195]:
print(arr2d.ndim)
print(arr2d.shape)

2
(2, 3)


In [196]:
# creating an ndarray with all zero

arr0s = np.zeros((3, 3))
print(arr0s)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [197]:
# creating an ndarray with all one

arr1s = np.ones((3, 3))
print(arr1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [198]:
# arange() method

arr_seq = np.arange(15)
print(arr_seq)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [199]:
# random.randn()
arr_rnd = np.random.randn(3, 4)
print(arr_rnd)

[[-0.16521287  0.83817549  0.21708834 -1.16407955]
 [ 0.68634674  0.76799038 -1.45138463  0.80319548]
 [ 0.81240906 -0.76493367 -0.03936846 -0.34159182]]


In [200]:
# eye

arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [201]:
np.random.rand(3, 3)

array([[0.39738064, 0.38885021, 0.44764754],
       [0.97863322, 0.76345846, 0.27573506],
       [0.37247069, 0.64187793, 0.65732764]])

In [202]:
# indexing and slicing
# 1d array

arr1d = np.array([2, 3, 4, 5, 6, 7, 9])

print(arr1d)
print(arr1d[2])
print(arr1d[2:5])
print(arr1d[:-1:2])

[2 3 4 5 6 7 9]
4
[4 5 6]
[2 4 6]


In [203]:
# indexing and slicing
# 2d array

arr2d = np.array(
        [[i+j*4 for i in range(4)] 
          for j in range(4)])
print(arr2d)
print(arr2d[0, 2])
print(arr2d[0, :])
print(arr2d[0:3, 1:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2
[0 1 2 3]
[[1]
 [5]
 [9]]


In [204]:
# Boolean Masking

arr = np.arange(5)
arr_bl = arr > 2
print(arr_bl)


[False False False  True  True]


In [205]:
# random user data in 4x2 matrix
arr_dat = np.random.rand(4, 2)
print(arr_dat)

# user id from 0 to 3
arr_id = np.arange(4)
print(arr_id)

# pick data for user id 2
print(arr_dat[arr_id == 2])

# pick data for user id 0 and 3
print(arr_dat[ (arr_id == 0) 
              | (arr_id == 3) ])

[[0.00990902 0.22058394]
 [0.04503549 0.25543932]
 [0.34141766 0.63466452]
 [0.09412491 0.3404472 ]]
[0 1 2 3]
[[0.34141766 0.63466452]]
[[0.00990902 0.22058394]
 [0.09412491 0.3404472 ]]


In [206]:
# Math and Stat Functions

arr = np.arange(16)
print(arr.sum())
print(arr.mean(), arr.std())
print(arr.min(), arr.max())

120
7.5 4.6097722286464435
0 15


In [207]:
print(arr.cumsum())
print(arr.cumprod())

[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### Vector and Matrix Computation with NumPY

In [208]:
# Vector arithmetic
arr1 = np.arange(5)
arr2 = np.array(range(5, 0, -1))
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[5 5 5 5 5]
[-5 -3 -1  1  3]
[0 4 6 6 4]
[0.         0.25       0.66666667 1.5        4.        ]


In [209]:
print(arr1 + 1)
print(arr1 * 2)
print(1 / arr2)

[1 2 3 4 5]
[0 2 4 6 8]
[0.2        0.25       0.33333333 0.5        1.        ]


In [210]:
print(arr1 > arr2)

[False False False  True  True]


In [211]:
# Matrix Manipulation & Computation

arr1 = np.arange(9)
print(arr1, arr1.shape)
mat1 = arr1.reshape(3, 3)
print(mat1, mat1.shape)

[0 1 2 3 4 5 6 7 8] (9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


In [212]:
mat2 = arr1.reshape(3, -1)
print(mat2, mat2.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


In [213]:
mat2 = arr1.reshape(4, -1)

ValueError: cannot reshape array of size 9 into shape (4,newaxis)

In [ ]:
# Linear Algebra

# transpose
m = np.arange(6).reshape(2, 3)
print(m, '\n', m.T)

In [ ]:
# dot product and matrix multiplication

m1 = np.arange(12).reshape(3, 4)
m2 = np.arange(8).reshape(4, 2) + 1
print(m1, '\n', m2)
print(np.dot(m1, m2))
print(m1.dot(m2))
print(m1 @ m2)

In [ ]:
# useful linear algebra functions
m = np.arange(16).reshape(4, -1) + 1
print(np.diag(m))
print(np.trace(m))
print(np.linalg.det(m))

## Numpy exercises

### Exercise 4.11n

Create below numpy arrays.
1. a vector containing number 10 to -10 in descending order.
2. a vector containing 10 zeros.
3. a vector containing 15 ones.
4. a 3x3 matrix:
```
5 6 7
8 9 10
11 12 13
```
5. a 3x3 matrix with random numbers
6. a 3x3 matrix (without typing every element):
```
1 4 7
2 5 8
3 6 9
```
7. a 3x3 matrix (without typing every element):
```
3 2 1
6 5 4
9 8 7
```
8. a 3x3 matrix (without typing every element):
```
9 8 7
6 5 4
3 2 1
```



In [ ]:
import numpy as np
# 1
Arr1=np.array(range(10,-11,-1))
print(Arr1)

# 2

Arr2=np.zeros((10,))
print(Arr2)

# 3
Arr3 = np.ones((10))
print(Arr3)

# 4


# 5


# 6


# 7


# 8


# 9


# 10



### Exercise 4.12n

Define a function ```to_nested_list()``` that takes a 2d array and returns the corresponding nested list.

For example:
```python
print(to_nested_list(np.array([[1, 2, 3], [4, 5, 6]]))
```

will output
```python
[[1, 2, 3],  [4, 5, 6]]
```


In [ ]:
def to_nested_list(ndarr):
    # write your code here
    

In [ ]:
# test case
arr = np.arange(6).reshape(2, -1) + 1

print(to_nested_list(arr))

# Pandas

#### Pandas Basics

In [ ]:
import numpy as np
import pandas as pd

#### Pandas Series

In [ ]:
# Series examples

data = pd.Series([0.1, 0.2, 0.3])
print(data)

In [ ]:
print(data.values, data.index)

In [ ]:
print(data[1])
print(data[0:3])
print(data[2:])

In [ ]:
# Index

val = np.arange(0, 5)
ind = val * 2
data = pd.Series(val, index=ind)
print(data)

In [ ]:
ind = [3, 9, 1, 10, 3]
data = pd.Series(val, index=ind)
print(data)
print(data[3])

In [ ]:
ind = ['a', 'b', 'c', 'd', 'e']
data = pd.Series(val, index=ind)
print(data) 

In [ ]:
# Creating pandas Series objects
import pandas as pd
import numpy as np
# general form: pd.Series(data, index=index)
# data can be：
# list
print("list")
print(pd.Series([1,3,8,11]))
# NumPy array
print("numpy array")
print(pd.Series(np.array([11,8,3,1])))
# scalar
print("scalar")
print(pd.Series(100))
print(pd.Series(100, index=range(3)))
# dictionary
print("dictionary")
print(pd.Series({0:1, 0.1:2, 'a':3}))

In [ ]:
# sizes must match

pd.Series([1, 2], index = [4,4])

#### Pandas DataFrame

In [ ]:
# first DataFrame example

df = pd.DataFrame({'name': ['John Doe', 'Jane Daw', 'Jack Go'],
                   'email': ['jdoe@em.net', 'jdaw@em.net', 'jgo@em.net']})
df

name        email
0  John Doe  jdoe@em.net
1  Jane Daw  jdaw@em.net
2   Jack Go   jgo@em.net

In [ ]:
# head and tail

print(df.head(4))
print(df.tail(1))

       name        email
0  John Doe  jdoe@em.net
1  Jane Daw  jdaw@em.net
2   Jack Go   jgo@em.net
      name       email
2  Jack Go  jgo@em.net


In [ ]:
# More DataFrame example

years = [2000, 2001, 2002, 2003, 2004]
population = {'area_1': [1.1, 1.2, 1.5, 1.7, 2.0],
        'area_2': [0.4, 0.5, 0.7, 0.6, 0.7]}
df = pd.DataFrame(population, index = years)
df

area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2002     1.5     0.7
2003     1.7     0.6
2004     2.0     0.7

In [ ]:
# DataFrame columns View

print(df.columns)

['area_1' 'area_2']


In [ ]:
# Single-column access
print(df['area_1'])
print(df.area_2)

# Multiple-column access
print(df[['area_1', 'area_2']])

2000    1.1
2001    1.2
2002    1.5
2003    1.7
2004    2.0
Name: area_1, dtype: float64
2000    0.4
2001    0.5
2002    0.7
2003    0.6
2004    0.7
Name: area_2, dtype: float64
      area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2002     1.5     0.7
2003     1.7     0.6
2004     2.0     0.7


In [ ]:
# Column addition

df['area_3'] = [1.8, 1.7, 1.5, 1.4, 1.4]
# df['area_4'] = ['a', 'b', 'c', 'd', 'e']
print(df)

      area_1  area_2  area_3
2000     1.1     0.4     1.8
2001     1.2     0.5     1.7
2002     1.5     0.7     1.5
2003     1.7     0.6     1.4
2004     2.0     0.7     1.4


In [ ]:
# DataFrame rows View

print(df.index)

Index([2000, 2001, 2002, 2003, 2004], dtype='int64')


In [ ]:
# row access with iloc

print(df.iloc[0])

area_1    1.1
area_2    0.4
area_3    1.8
area_4      a
Name: 2000, dtype: object


In [ ]:
print(df.iloc[ [1, 3] ])

      area_1  area_2  area_3 area_4
2001     1.2     0.5     1.7      b
2003     1.7     0.6     1.4      d


In [ ]:
print(df.iloc[2:5])

      area_1  area_2  area_3 area_4
2002     1.5     0.7     1.5      c
2003     1.7     0.6     1.4      d
2004     2.0     0.7     1.4      e


In [ ]:
# row access with loc

print(df.loc[2000])

area_1    1.1
area_2    0.4
area_3    1.8
area_4      a
Name: 2000, dtype: object


In [ ]:
print(df.loc[ [2001, 2003]])

      area_1  area_2  area_3 area_4
2001     1.2     0.5     1.7      b
2003     1.7     0.6     1.4      d


In [ ]:
print(df.loc[2002: 2004])

      area_1  area_2  area_3 area_4
2002     1.5     0.7     1.5      c
2003     1.7     0.6     1.4      d
2004     2.0     0.7     1.4      e


In [ ]:
# Flexible Data Selection
# iloc

print(df.iloc[0, 0]) # Devina notes: Row and column combinatsion
print(df.iloc[ [1, 3] ])

1.1
      area_1  area_2  area_3 area_4
2001     1.2     0.5     1.7      b
2003     1.7     0.6     1.4      d


In [ ]:
print(df.iloc[:3, -1]) # Devina notes: :3 meaning rows and -1 meaning last column/series

2000    a
2001    b
2002    c
Name: area_4, dtype: object


In [ ]:
print(df.iloc[[0, 2],1:3]) # Devina notes: dnt use [] when giving range

      area_2  area_3
2000     0.4     1.8
2002     0.7     1.5


In [ ]:
# loc

print(df.loc[2001, 'area_2'])

In [ ]:
print(df.loc[2001:2002, 'area_3'])

In [ ]:
print(df.loc[[2000, 2001, 2003], :'area_2'])

      area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2003     1.7     0.6


In [ ]:
df.ix?

Object `df.ix` not found.


In [ ]:
# Index

print(df.columns)
print(type(df.columns))
print(df.index)
print(type(df.index))

Index(['area_1', 'area_2', 'area_3', 'area_4'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
Index([2000, 2001, 2002, 2003, 2004], dtype='int64')
<class 'pandas.core.indexes.base.Index'>


In [ ]:
# Immutable

df.index[0] = 1999

TypeError: Index does not support mutable operations

In [ ]:
# More DataFrame example

years = [2000, 2001, 2002, 2003, 2004]
population = {'area_1': [1.1, 1.2, 1.5, 1.7, 2.0],
        'area_2': [0.4, 0.5, 0.7, 0.6, 0.7]}
df = pd.DataFrame(population, index = years)
df

area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2002     1.5     0.7
2003     1.7     0.6
2004     2.0     0.7

In [ ]:
# Replaceable



print(df)
df.index = range(len(df)) # len(df) gives the number of rows of DataFrame
df.columns = ['a1', 'a2']
df

   area_1  area_2
0     1.1     0.4
1     1.2     0.5
2     1.5     0.7
3     1.7     0.6
4     2.0     0.7


a1   a2
0  1.1  0.4
1  1.2  0.5
2  1.5  0.7
3  1.7  0.6
4  2.0  0.7

In [ ]:
# setting a column as index

df['year'] = range(1900, 1905) # create new column year
df

area_1  area_2  year
2000     1.1     0.4  1900
2001     1.2     0.5  1901
2002     1.5     0.7  1902
2003     1.7     0.6  1903
2004     2.0     0.7  1904

In [ ]:
df.set_index('year') # creates a view

area_1  area_2
year                
1900     1.1     0.4
1901     1.2     0.5
1902     1.5     0.7
1903     1.7     0.6
1904     2.0     0.7

In [ ]:
df # df is unchanged without setting inplace to True

area_1  area_2  year
2000     1.1     0.4  1900
2001     1.2     0.5  1901
2002     1.5     0.7  1902
2003     1.7     0.6  1903
2004     2.0     0.7  1904

In [ ]:
df.set_index('year',inplace = True)

KeyError: "None of ['year'] are in the columns"

In [ ]:
df

area_1  area_2  year
2000     1.1     0.4  1900
2001     1.2     0.5  1901
2002     1.5     0.7  1902
2003     1.7     0.6  1903
2004     2.0     0.7  1904

In [ ]:
# Filtering

info = {'name': ['Alicia', 'Adam', 'Ashley'],
        'age': [10, 12, 9],
        'height': [155, 158, 152],
        'weight': [45, 42, 52]}

df = pd.DataFrame(info)
df
df.set_index('name', inplace=True)
df


age  height  weight
name                       
Alicia   10     155      45
Adam     12     158      42
Ashley    9     152      52

In [ ]:
# Filter Mask

print(df['age'] >= 10)

name
Alicia     True
Adam       True
Ashley    False
Name: age, dtype: bool


In [ ]:
print(df >= 10)

          age  height  weight
name                         
Alicia   True    True    True
Adam     True    True    True
Ashley  False    True    True


In [ ]:
ft = (df['age'] >= 10) & (df['height'] < 158)
print(ft)

name
Alicia     True
Adam      False
Ashley    False
dtype: bool


In [ ]:
# Data selection with filter mask---one way

print(df[df['age'] >= 10])

        age  height  weight
name                       
Alicia   10     155      45
Adam     12     158      42


In [ ]:
print(df.loc[df['age'] >= 10])---another way

        age  height  weight
name                       
Alicia   10     155      45
Adam     12     158      42


In [ ]:
print(df.loc[df['age'] >= 10, 'height'])# only height

name
Alicia    155
Adam      158
Name: height, dtype: int64


In [ ]:
print(df.loc[df['height'] >= 10, ['age', 'weight']])

        age  weight
name               
Alicia   10      45
Adam     12      42
Ashley    9      52


In [ ]:
# Updating rows

names = {'first name': 
            ['Josh', 'John', 'Jane'],
         'last name': 
            ['Smith', 'Doe', 'Doe']}
df = pd.DataFrame(names)
df

first name last name
0       Josh     Smith
1       John       Doe
2       Jane       Doe

In [ ]:
df[df['last name'] == 'Smith']['last name'] = 'Anderson'#??????

C:\Users\TyagiAkash\AppData\Local\Temp\ipykernel_13620\1171294678.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['last name'] == 'Smith']['last name'] = 'Anderson'#??????


In [ ]:
df

first name last name
0       Josh     Smith
1       John       Doe
2       Jane       Doe

In [ ]:
df.loc[0] = ['Jason', 'Anderson']
df

first name last name
0      Jason  Anderson
1       John       Doe
2       Jane       Doe

In [ ]:
df.iloc[0] = ['Josh', 'Smith']
df

first name last name
0       Josh     Smith
1       John       Doe
2       Jane       Doe

In [ ]:
df.loc[0, ['last name']] = 'Anderson'
df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [ ]:
df['last name'] = list(df['last name'])[::-1]##?????
df

first name last name
0       Josh       Doe
1       John       Doe
2       Jane  Anderson

In [ ]:
df = pd.DataFrame(
    {'first name': ['Josh', 'John', 'Jane'],
     'last name': ['Anderson', 'Doe', 'Doe']}
)
df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [ ]:
dir(df['last name'].str)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data',
 '_doc_args',
 '_freeze',
 '_get_series_list',
 '_index',
 '_inferred_dtype',
 '_is_categorical',
 '_is_string',
 '_name',
 '_orig',
 '_parent',
 '_validate',
 '_wrap_result',
 'capitalize',
 'casefold',
 'cat',
 'center',
 'contains',
 'count',
 'decode',
 'encode',
 'endswith',
 'extract',
 'extractall',
 'find',
 'findall',
 'fullmatch',
 'get',
 'get_dummies',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'len',
 'ljust',
 'lower',
 'lstrip',
 'ma

In [ ]:
df['last name'] = df['last name'].str.lower()
df


first name last name
0       Josh  anderson
1       John       doe
2       Jane       doe

In [ ]:
# Apply, map, applymap, replace##????

# pd.Seires.apply()
df['last name'] = df['last name'].apply(str.title)

df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [ ]:
def change_Josh(fname):
    return 'Joe' if fname == 'Josh' else fname

df['first name'] = df['first name'].apply(change_Josh)

df

first name last name
0        Joe  Anderson
1       John       Doe
2       Jane       Doe

In [ ]:
df['first name'] = df['first name'].apply(lambda s: 'Josh' if s == 'Joe' else s)# s variable is used
df

first name last name
0       Josh     Smith
1       John       Doe
2       Jane       Doe

In [ ]:
import pandas as pd

def calc_sum(x):
  return x.sum()

data = {
  "x": [50, 40, 30],
  "y": [300, 1112, 42]
}

df = pd.DataFrame(data)

x = df.apply(calc_sum)

print(df)
print(x)

    x     y
0  50   300
1  40  1112
2  30    42
x     120
y    1454
dtype: int64


In [ ]:
# pd.DataFrame.apply()???????? how to
df.apply(len)

first name    3
last name     3
dtype: int64

In [ ]:
df.apply(len, axis='index')#???

first name    3
last name     3
dtype: int64

In [ ]:
df.apply(len, axis=1)##??????,0 for rows ,1 for columns

0    2
1    2
2    2
dtype: int64

In [ ]:
df.apply(len, axis=0)##??????,0 for rows ,1 for columns

first name    3
last name     3
dtype: int64

In [ ]:
df.apply(lambda ser: max(ser.apply(len)))#ser is used as variable

first name    4
last name     8
dtype: int64

In [ ]:
# pandas.DataFrame.applymap()
df['first name'] = df['first name'].apply(lambda s: 'Josh' if s == 'Joe' else s)# s variable is used
df
print(df.applymap(str.upper))

  first name last name
0       JOSH  ANDERSON
1       JOHN       DOE
2       JANE       DOE


C:\Users\TyagiAkash\AppData\Local\Temp\ipykernel_13620\3213356426.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  print(df.applymap(str.upper))


In [ ]:
print(df.applymap(lambda s: s[0]))#???


  first name last name
0          J         A
1          J         D
2          J         D


C:\Users\TyagiAkash\AppData\Local\Temp\ipykernel_13620\1495068663.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  print(df.applymap(lambda s: s[0]))


In [ ]:
df = pd.DataFrame(
    {'first name': ['Josh', 'John', 'Jane'],
     'last name': ['Anderson', 'Doe', 'Doe']}
)
df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [ ]:
# pandas.Series.map()

print(df['first name'].map({'Josh': 'Joe', 'John': 'Jay'}))
df

0    Joe
1    Jay
2    NaN
Name: first name, dtype: object


first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [ ]:
s = pd.Series({"Josh":'Joe', 'John': 'Jay'})
s

Josh    Joe
John    Jay
dtype: object

In [ ]:
print(df['first name'].map(s))

0    Joe
1    Jay
2    NaN
Name: first name, dtype: object


In [ ]:
# pandas.Series.replace()

print(df['first name'].replace({'Josh': 'Joe', 'John': 'Jay'}))

0     Joe
1     Jay
2    Jane
Name: first name, dtype: object


In [ ]:
# Adding columns

df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [ ]:
df['full name'] = df['first name'] + ' ' + df['last name']
df

first name last name      full name
0       Josh  Anderson  Josh Anderson
1       John       Doe       John Doe
2       Jane       Doe       Jane Doe

In [ ]:
df['year in'] = [2005, 2011, 2019]
df

first name last name      full name  year in  gender
0       Josh  Anderson  Josh Anderson     2005    male
1       John       Doe       John Doe     2011     NaN
2       Jane       Doe       Jane Doe     2019  female

In [ ]:
df['email'] = df['first name'].str.lower() +'.' \
            + df['last name'].str.lower() + \
            + df['year in'].apply(str) + '@company.com'
df

TypeError: bad operand type for unary +: 'str'

In [ ]:
# assigning a Series to the new column

emp_sex = pd.Series({0: 'male', 2: 'female'})
df['gender'] = emp_sex
df

first name last name      full name  year in  gender
0       Josh  Anderson  Josh Anderson     2005    male
1       John       Doe       John Doe     2011     NaN
2       Jane       Doe       Jane Doe     2019  female

In [ ]:
# Appending a DataFrame to Another

df2 = pd.DataFrame({'first name': ['Ron', 'Nick'],
                    'last name': ['James', 'Simons'],
                    'full name': ['Ron James', 'Nick Simons'],
                    'year in': [2010, 2011],
                    'email': ['ron.james2010@company.com', 
                              'nick.simons2011@company.com'],
                    'gender': ['male', 'male']
                   }
                  )
df2

first name last name    full name  year in                        email  \
0        Ron     James    Ron James     2010    ron.james2010@company.com   
1       Nick    Simons  Nick Simons     2011  nick.simons2011@company.com   

  gender  
0   male  
1   male

In [ ]:
df.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'

In [214]:
df.append(df2, ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
df = df.append(df2, ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
df

In [215]:
# Removing columns or rows
# Series

df['gender'].drop([3, 4])

KeyError: '[3, 4] not found in axis'

In [ ]:
# DataFrame

df.drop([3, 4])

In [ ]:
df.drop(df[df['gender'] == 'male'].index)

In [ ]:
df.drop('year in', axis = 1)

In [216]:
df.drop('year in', axis=1, inplace=True)
df

first name last name      full name  gender
0       Josh  Anderson  Josh Anderson    male
1       John       Doe       John Doe     NaN
2       Jane       Doe       Jane Doe  female

In [ ]:
# Sorting Data

df

In [ ]:
df.sort_values(by = 'last name')

In [ ]:
df.sort_values(by=['last name', 'first name'])

In [ ]:
df.sort_values(by=['last name', 'first name'], ascending=[True, False])

In [ ]:
df.sort_values(by='first name', inplace=True)

In [ ]:
df

In [ ]:
# pandas.DataFrame.sort_index()

df.sort_index(inplace=True)
df

## Pandas exercises

### Exercise 4.11p

1. Given two lists of the same size, ```l1``` and ```l2```, use ```l1``` as the index and ```l2``` as the data to create a pandas Series ```s```.

2. create another pandas Series ```s1``` from ```s```, using the index in ```s``` as data in ```s``` and the data in ```s``` as index in ```s1```.

3. multiply all items in ```s``` by 2.

4. change the index to lower-case letters 'a', 'b', ..., 'h'.

5. define a function to add 1 to first item in ```s```, 2 to second item, 3 to third item, etc.

Remove the underline and fill in your code. Each underline is for one line of code.


In [ ]:
l1 = list(range(5, 20, 2))
l2 = [5*n for n in range(len(l1))]
print(l1, l2)

# 1
s = ___________________ # remove the underline and fill your code
print(s)

# 2
s1 = __________________ # remove the underline and fill your code
print(s1)

# 3
s = ___________________ # remove the underline and fill your code
print(s)

# 4
s.index = ___________________ # remove the underline and fill your code
print(s)

# 5
def add_n(ser):
    # write your code here


add_n(s)
print(s)



### Exercise 4.12p

1. Given a dictionary containing student names and their marks of three courses, create a DataFrame with their names as index and course names as columns.
```python
marks = { 'Names': ['James', 'Andrew', 'Bob', 'Carlson'],
          'English': [58, 62, 77, 65],
          'Chinese': [55, 32, 64, 80],
          'Math': [61, 70, 81, 54]}
```

2. Given a dictionary containing students names and their marks of three courses, create a DataFrame with their names as index and course names as columns. Use the same column names as ex 2.1.
```
marks = {'James': [58, 55, 61],
         'Andrew': [62, 32, 70],
         'Bob': [77, 64, 81],
         'Carlson': [65, 80, 54]}
```


In [ ]:
# 1
marks = { 'Names': ['James', 'Andrew', 'Bob', 'Carlson'],
          'English': [58, 62, 77, 65],
          'Chinese': [55, 32, 64, 80],
          'Math': [61, 70, 81, 54]}

df = ______________________ # remove the underline and fill your code
df.set_index(_____________________) # remove the underline and fill your code
print(df)

# 2
marks = {'James': [58, 55, 61],
         'Andrew': [62, 32, 70],
         'Bob': [77, 64, 81],
         'Carlson': [65, 80, 54]}

df = pd.DataFrame(_________________________, # remove the underline and fill your code
                  index=________________________, # remove the underline and fill your code
                  columns=['English', 'Chinese', 'Math'])
print(df)

In [ ]:
# 1
marks = { 'Names': ['James', 'Andrew', 'Bob', 'Carlson'],
          'English': [58, 62, 77, 65],
          'Chinese': [55, 32, 64, 80],
          'Math': [61, 70, 81, 54]}

df = pd.DataFrame(marks)
df.set_index('Names', inplace=True)
print(df)

# 2
marks = {'James': [58, 55, 61],
         'Andrew': [62, 32, 70],
         'Bob': [77, 64, 81],
         'Carlson': [65, 80, 54]}

df = pd.DataFrame(marks.values(),
                  index=marks.keys(),
                  columns=['English', 'Chinese', 'Math'])
print(df)

In [ ]:
s = pd.Series( [ 1, 2, 1, 2, 1, 3])

In [ ]:
s = s.map({1: 1, 2: 3})

In [ ]:
s[5] = np.nan
s