In [39]:
def add_list(size_of_list):
    l1 = list(range(size_of_list))
    l2 = list(range(size_of_list))
    l = [l1[i] + l2[i] for i in range(size_of_list)]
    return l

# Numpy

#### Motivation For Numpy

In [40]:
def add_list(size_of_list):
    l1 = list(range(size_of_list))
    l2 = list(range(size_of_list))
    l = [l1[i] + l2[i] for i in range(size_of_list)]
    return l

In [41]:
size = 10000000

In [42]:
%%time
add_list(size)[0:10]

CPU times: total: 6.69 s
Wall time: 6.9 s


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [43]:
import numpy as np

In [44]:
def add_ndarray(size_of_array):
    l1 = np.arange(size_of_array)
    l2 = np.arange(size_of_array)
    return l1 + l2

In [45]:
%%time
add_ndarray(size)[:10]

CPU times: total: 62.5 ms
Wall time: 71.7 ms


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

####  NumPy ndarrays

In [46]:
import numpy as np

In [47]:
arr = np.array([0, 1, 1, 2, 3, 5])
print(arr)

[0 1 1 2 3 5]


In [48]:
arr2d = np.array([ [0, 1, 1], 
                   [2, 3, 5] ])
print(arr2d)

[[0 1 1]
 [2 3 5]]


In [49]:
print(arr.ndim)
print(arr.shape)

1
(6,)


In [50]:
print(arr2d.ndim)
print(arr2d.shape)

2
(2, 3)


In [51]:
# creating an ndarray with all zero

arr0s = np.zeros((3, 3))
print(arr0s)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
# creating an ndarray with all one

arr1s = np.ones((3, 3))
print(arr1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
# arange() method

arr_seq = np.arange(15)
print(arr_seq)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [54]:
# random.randn()
arr_rnd = np.random.randn(3, 4)
print(arr_rnd)

[[ 0.86300436  0.41309348  0.40029024  1.58331284]
 [-1.57707801 -1.38344425 -0.45993274  0.25823605]
 [ 0.62683499  1.34269383 -0.17310374 -1.66497118]]


In [55]:
# eye

arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
np.random.rand(3, 3)

array([[0.54635363, 0.50426092, 0.38622092],
       [0.13609346, 0.20621812, 0.72309609],
       [0.73654129, 0.81416428, 0.30657215]])

In [57]:
# indexing and slicing
# 1d array

arr1d = np.array([2, 3, 4, 5, 6, 7, 9])

print(arr1d)
print(arr1d[2])
print(arr1d[2:5])
print(arr1d[:-1:2])

[2 3 4 5 6 7 9]
4
[4 5 6]
[2 4 6]


In [58]:
# indexing and slicing
# 2d array

arr2d = np.array(
        [[i+j*4 for i in range(4)] 
          for j in range(4)])
print(arr2d)
print(arr2d[0, 2])
print(arr2d[0, :])
print(arr2d[0:3, 1:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2
[0 1 2 3]
[[1]
 [5]
 [9]]


In [59]:
# Boolean Masking

arr = np.arange(5)
arr_bl = arr > 2
print(arr_bl)


[False False False  True  True]


In [60]:
# random user data in 4x2 matrix
arr_dat = np.random.rand(4, 2)
print(arr_dat)

# user id from 0 to 3
arr_id = np.arange(4)
print(arr_id)

# pick data for user id 2
print(arr_dat[arr_id == 2])

# pick data for user id 0 and 3
print(arr_dat[ (arr_id == 0) 
              | (arr_id == 3) ])

[[0.2632619  0.16176634]
 [0.81280938 0.29713282]
 [0.11481253 0.01018925]
 [0.0535972  0.49375906]]
[0 1 2 3]
[[0.11481253 0.01018925]]
[[0.2632619  0.16176634]
 [0.0535972  0.49375906]]


In [61]:
# Math and Stat Functions

arr = np.arange(16)
print(arr.sum())
print(arr.mean(), arr.std())
print(arr.min(), arr.max())

120
7.5 4.6097722286464435
0 15


In [62]:
print(arr.cumsum())
print(arr.cumprod())

[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### Vector and Matrix Computation with NumPY

In [63]:
# Vector arithmetic
arr1 = np.arange(5)
arr2 = np.array(range(5, 0, -1))
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[5 5 5 5 5]
[-5 -3 -1  1  3]
[0 4 6 6 4]
[0.         0.25       0.66666667 1.5        4.        ]


In [64]:
print(arr1 + 1)
print(arr1 * 2)
print(1 / arr2)

[1 2 3 4 5]
[0 2 4 6 8]
[0.2        0.25       0.33333333 0.5        1.        ]


In [65]:
print(arr1 > arr2)

[False False False  True  True]


In [66]:
# Matrix Manipulation & Computation

arr1 = np.arange(9)
print(arr1, arr1.shape)
mat1 = arr1.reshape(3, 3)
print(mat1, mat1.shape)

[0 1 2 3 4 5 6 7 8] (9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


In [67]:
mat2 = arr1.reshape(3, -1)
print(mat2, mat2.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


In [68]:
mat2 = arr1.reshape(4, -1)

ValueError: cannot reshape array of size 9 into shape (4,newaxis)

In [ ]:
# Linear Algebra

# transpose
m = np.arange(6).reshape(2, 3)
print(m, '\n', m.T)

In [ ]:
# dot product and matrix multiplication

m1 = np.arange(12).reshape(3, 4)
m2 = np.arange(8).reshape(4, 2) + 1
print(m1, '\n', m2)
print(np.dot(m1, m2))
print(m1.dot(m2))
print(m1 @ m2)

In [ ]:
# useful linear algebra functions
m = np.arange(16).reshape(4, -1) + 1
print(np.diag(m))
print(np.trace(m))
print(np.linalg.det(m))

## Numpy exercises

### Exercise 4.11n

Create below numpy arrays.
1. a vector containing number 10 to -10 in descending order.
2. a vector containing 10 zeros.
3. a vector containing 15 ones.
4. a 3x3 matrix:
```
5 6 7
8 9 10
11 12 13
```
5. a 3x3 matrix with random numbers
6. a 3x3 matrix (without typing every element):
```
1 4 7
2 5 8
3 6 9
```
7. a 3x3 matrix (without typing every element):
```
3 2 1
6 5 4
9 8 7
```
8. a 3x3 matrix (without typing every element):
```
9 8 7
6 5 4
3 2 1
```



In [ ]:
import numpy as np
# 1
Arr1=np.array(range(10,-11,-1))
print(Arr1)

# 2

Arr2=np.zeros((10,))
print(Arr2)

# 3
Arr3 = np.ones((10))
print(Arr3)

# 4


# 5


# 6


# 7


# 8


# 9


# 10



### Exercise 4.12n

Define a function ```to_nested_list()``` that takes a 2d array and returns the corresponding nested list.

For example:
```python
print(to_nested_list(np.array([[1, 2, 3], [4, 5, 6]]))
```

will output
```python
[[1, 2, 3],  [4, 5, 6]]
```


In [ ]:
def to_nested_list(ndarr):
    # write your code here
    

In [ ]:
# test case
arr = np.arange(6).reshape(2, -1) + 1

print(to_nested_list(arr))

# Pandas

#### Pandas Basics

In [ ]:
import numpy as np
import pandas as pd

#### Pandas Series

In [ ]:
# Series examples

data = pd.Series([0.1, 0.2, 0.3])
print(data)

In [ ]:
print(data.values, data.index)

In [ ]:
print(data[1])
print(data[0:3])
print(data[2:])

In [ ]:
# Index

val = np.arange(0, 5)
ind = val * 2
data = pd.Series(val, index=ind)
print(data)

In [ ]:
ind = [3, 9, 1, 10, 3]
data = pd.Series(val, index=ind)
print(data)
print(data[3])

In [ ]:
ind = ['a', 'b', 'c', 'd', 'e']
data = pd.Series(val, index=ind)
print(data) 

In [ ]:
# Creating pandas Series objects
import pandas as pd
import numpy as np
# general form: pd.Series(data, index=index)
# data can be：
# list
print("list")
print(pd.Series([1,3,8,11]))
# NumPy array
print("numpy array")
print(pd.Series(np.array([11,8,3,1])))
# scalar
print("scalar")
print(pd.Series(100))
print(pd.Series(100, index=range(3)))
# dictionary
print("dictionary")
print(pd.Series({0:1, 0.1:2, 'a':3}))

In [ ]:
# sizes must match

pd.Series([1, 2], index = [4,4])

#### Pandas DataFrame

In [ ]:
# first DataFrame example

df = pd.DataFrame({'name': ['John Doe', 'Jane Daw', 'Jack Go'],
                   'email': ['jdoe@em.net', 'jdaw@em.net', 'jgo@em.net']})
df

name        email
0  John Doe  jdoe@em.net
1  Jane Daw  jdaw@em.net
2   Jack Go   jgo@em.net

In [ ]:
# head and tail

print(df.head(4))
print(df.tail(1))

       name        email
0  John Doe  jdoe@em.net
1  Jane Daw  jdaw@em.net
2   Jack Go   jgo@em.net
      name       email
2  Jack Go  jgo@em.net


In [ ]:
# More DataFrame example

years = [2000, 2001, 2002, 2003, 2004]
population = {'area_1': [1.1, 1.2, 1.5, 1.7, 2.0],
        'area_2': [0.4, 0.5, 0.7, 0.6, 0.7]}
df = pd.DataFrame(population, index = years)
df

area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2002     1.5     0.7
2003     1.7     0.6
2004     2.0     0.7

In [ ]:
# DataFrame columns View

print(df.columns)

['area_1' 'area_2']


In [ ]:
# Single-column access
print(df['area_1'])
print(df.area_2)

# Multiple-column access
print(df[['area_1', 'area_2']])

2000    1.1
2001    1.2
2002    1.5
2003    1.7
2004    2.0
Name: area_1, dtype: float64
2000    0.4
2001    0.5
2002    0.7
2003    0.6
2004    0.7
Name: area_2, dtype: float64
      area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2002     1.5     0.7
2003     1.7     0.6
2004     2.0     0.7


In [ ]:
# Column addition

df['area_3'] = [1.8, 1.7, 1.5, 1.4, 1.4]
df['area_4'] = ['a', 'b', 'c', 'd', 'e']
print(df)

      area_1  area_2  area_3 area_4
2000     1.1     0.4     1.8      a
2001     1.2     0.5     1.7      b
2002     1.5     0.7     1.5      c
2003     1.7     0.6     1.4      d
2004     2.0     0.7     1.4      e


In [ ]:
# DataFrame rows View

print(df.index)

Index([2000, 2001, 2002, 2003, 2004], dtype='int64')


In [ ]:
# row access with iloc

print(df.iloc[0])

area_1    1.1
area_2    0.4
area_3    1.8
area_4      a
Name: 2000, dtype: object


In [ ]:
print(df.iloc[ [1, 3] ])

      area_1  area_2  area_3 area_4
2001     1.2     0.5     1.7      b
2003     1.7     0.6     1.4      d


In [ ]:
print(df.iloc[2:5])

      area_1  area_2  area_3 area_4
2002     1.5     0.7     1.5      c
2003     1.7     0.6     1.4      d
2004     2.0     0.7     1.4      e


In [ ]:
# row access with loc

print(df.loc[2000])

area_1    1.1
area_2    0.4
area_3    1.8
area_4      a
Name: 2000, dtype: object


In [69]:
print(df.loc[ [2001, 2003]])

      area_1  area_2  area_3 area_4
2001     1.2     0.5     1.7      b
2003     1.7     0.6     1.4      d


In [70]:
print(df.loc[2002: 2004])

      area_1  area_2  area_3 area_4
2002     1.5     0.7     1.5      c
2003     1.7     0.6     1.4      d
2004     2.0     0.7     1.4      e


In [74]:
# Flexible Data Selection
# iloc

print(df.iloc[0, 0]) # Devina notes: Row and column combinatsion
print(df.iloc[ [1, 3] ])

1.1
      area_1  area_2  area_3 area_4
2001     1.2     0.5     1.7      b
2003     1.7     0.6     1.4      d


In [78]:
print(df.iloc[:3, -1]) # Devina notes: :3 meaning rows and -1 meaning last column/series

2000    a
2001    b
2002    c
Name: area_4, dtype: object


In [89]:
print(df.iloc[[0, 2],1:3]) # Devina notes: dnt use [] when giving range

      area_2  area_3
2000     0.4     1.8
2002     0.7     1.5


In [ ]:
# loc

print(df.loc[2001, 'area_2'])

In [ ]:
print(df.loc[2001:2002, 'area_3'])

In [ ]:
print(df.loc[[2000, 2001, 2003], :'area_2'])

In [ ]:
df.ix?

In [ ]:
# Index

print(df.columns)
print(type(df.columns))
print(df.index)
print(type(df.index))

In [ ]:
# Immutable

df.index[0] = 1999

In [ ]:
# Replaceable

df.index = range(len(df)) # len(df) gives the number of rows of DataFrame
df.columns = ['a1', 'a2', 'a3']
df

In [ ]:
# setting a column as index

df['year'] = range(2000, 2005) # create new column year

In [ ]:
df.set_index('year') # column is removed after being set as index

In [ ]:
df # df is unchanged without setting inplace to True

In [ ]:
df.set_index('year',inplace = True)

In [ ]:
df

In [ ]:
# Filtering

info = {'name': ['Alicia', 'Adam', 'Ashley'],
        'age': [10, 12, 9],
        'height': [155, 158, 152],
        'weight': [45, 42, 52]}

df = pd.DataFrame(info)
df.set_index('name', inplace=True)
df


In [ ]:
# Filter Mask

print(df['age'] >= 10)

In [ ]:
print(df >= 10)

In [ ]:
ft = (df['age'] >= 10) & (df['height'] < 158)
print(ft)

In [ ]:
# Data selection with filter mask

print(df[df['age'] >= 10])

In [ ]:
print(df.loc[df['age'] >= 10])

In [ ]:
print(df.loc[df['age'] >= 10, 'height'])

In [ ]:
print(df.loc[df['height'] >= 10, ['age', 'weight']])

In [ ]:
# Updating rows

names = {'first name': 
            ['Josh', 'John', 'Jane'],
         'last name': 
            ['Smith', 'Doe', 'Doe']}
df = pd.DataFrame(names)
df

In [ ]:
df[df['last name'] == 'Smith']['last name'] = 'Anderson'

In [ ]:
df

In [ ]:
df.loc[0] = ['Jason', 'Anderson']
df

In [ ]:
df.iloc[0] = ['Josh', 'Smith']
df

In [ ]:
df.loc[0, ['last name']] = 'Anderson'
df

In [ ]:
df['last name'] = list(df['last name'])[::-1]
df

In [ ]:
df = pd.DataFrame(
    {'first name': ['Josh', 'John', 'Jane'],
     'last name': ['Anderson', 'Doe', 'Doe']}
)
df

In [ ]:
dir(df['last name'].str)

In [ ]:
df['last name'] = df['last name'].str.lower()
df


In [ ]:
# Apply, map, applymap, replace

# pd.Seires.apply()
df['last name'] = df['last name'].apply(str.title)

df

In [ ]:
def change_Josh(fname):
    return 'Joe' if fname == 'Josh' else fname

df['first name'] = df['first name'].apply(change_Josh)

df

In [ ]:
df['first name'] = df['first name'].apply(lambda s: 'Josh' if s == 'Joe' else s)
df

In [ ]:
# pd.DataFrame.apply()

df.apply(len)

In [ ]:
df.apply(len, axis='index')

In [ ]:
df.apply(len, axis=1)

In [ ]:
df.apply(lambda ser: max(ser.apply(len)))

In [ ]:
# pandas.DataFrame.applymap()

print(df.applymap(str.upper))

In [ ]:
print(df.applymap(lambda s: s[0]))


In [ ]:
# pandas.Series.map()

print(df['first name'].map({'Josh': 'Joe', 'John': 'Jay'}))

In [ ]:
s = pd.Series({"Josh":'Joe', 'John': 'Jay'})
s

In [ ]:
print(df['first name'].map(s))

In [ ]:
# pandas.Series.replace()

print(df['first name'].replace({'Josh': 'Joe', 'John': 'Jay'}))

In [ ]:
# Adding columns

df

In [ ]:
df['full name'] = df['first name'] + ' ' + df['last name']
df

In [ ]:
df['year in'] = [2005, 2011, 2019]
df

In [ ]:
df['email'] = df['first name'].str.lower() +'.' \
            + df['last name'].str.lower() + \
            + df['year in'].apply(str) + '@company.com'
df

In [ ]:
# assigning a Series to the new column

emp_sex = pd.Series({0: 'male', 2: 'female'})
df['gender'] = emp_sex
df

In [ ]:
# Appending a DataFrame to Another

df2 = pd.DataFrame({'first name': ['Ron', 'Nick'],
                    'last name': ['James', 'Simons'],
                    'full name': ['Ron James', 'Nick Simons'],
                    'year in': [2010, 2011],
                    'email': ['ron.james2010@company.com', 
                              'nick.simons2011@company.com'],
                    'gender': ['male', 'male']
                   }
                  )
df2

In [ ]:
df.append(df2)

In [ ]:
df.append(df2, ignore_index=True)

In [ ]:
df = df.append(df2, ignore_index=True)

In [ ]:
df

In [ ]:
# Removing columns or rows
# Series

df['gender'].drop([3, 4])

In [ ]:
# DataFrame

df.drop([3, 4])

In [ ]:
df.drop(df[df['gender'] == 'male'].index)

In [ ]:
df.drop('year in', axis = 1)

In [ ]:
df.drop('year in', axis=1, inplace=True)
df

In [ ]:
# Sorting Data

df

In [ ]:
df.sort_values(by = 'last name')

In [ ]:
df.sort_values(by=['last name', 'first name'])

In [ ]:
df.sort_values(by=['last name', 'first name'], ascending=[True, False])

In [ ]:
df.sort_values(by='first name', inplace=True)

In [ ]:
df

In [ ]:
# pandas.DataFrame.sort_index()

df.sort_index(inplace=True)
df

## Pandas exercises

### Exercise 4.11p

1. Given two lists of the same size, ```l1``` and ```l2```, use ```l1``` as the index and ```l2``` as the data to create a pandas Series ```s```.

2. create another pandas Series ```s1``` from ```s```, using the index in ```s``` as data in ```s``` and the data in ```s``` as index in ```s1```.

3. multiply all items in ```s``` by 2.

4. change the index to lower-case letters 'a', 'b', ..., 'h'.

5. define a function to add 1 to first item in ```s```, 2 to second item, 3 to third item, etc.

Remove the underline and fill in your code. Each underline is for one line of code.


In [ ]:
l1 = list(range(5, 20, 2))
l2 = [5*n for n in range(len(l1))]
print(l1, l2)

# 1
s = ___________________ # remove the underline and fill your code
print(s)

# 2
s1 = __________________ # remove the underline and fill your code
print(s1)

# 3
s = ___________________ # remove the underline and fill your code
print(s)

# 4
s.index = ___________________ # remove the underline and fill your code
print(s)

# 5
def add_n(ser):
    # write your code here


add_n(s)
print(s)



### Exercise 4.12p

1. Given a dictionary containing student names and their marks of three courses, create a DataFrame with their names as index and course names as columns.
```python
marks = { 'Names': ['James', 'Andrew', 'Bob', 'Carlson'],
          'English': [58, 62, 77, 65],
          'Chinese': [55, 32, 64, 80],
          'Math': [61, 70, 81, 54]}
```

2. Given a dictionary containing students names and their marks of three courses, create a DataFrame with their names as index and course names as columns. Use the same column names as ex 2.1.
```
marks = {'James': [58, 55, 61],
         'Andrew': [62, 32, 70],
         'Bob': [77, 64, 81],
         'Carlson': [65, 80, 54]}
```


In [ ]:
# 1
marks = { 'Names': ['James', 'Andrew', 'Bob', 'Carlson'],
          'English': [58, 62, 77, 65],
          'Chinese': [55, 32, 64, 80],
          'Math': [61, 70, 81, 54]}

df = ______________________ # remove the underline and fill your code
df.set_index(_____________________) # remove the underline and fill your code
print(df)

# 2
marks = {'James': [58, 55, 61],
         'Andrew': [62, 32, 70],
         'Bob': [77, 64, 81],
         'Carlson': [65, 80, 54]}

df = pd.DataFrame(_________________________, # remove the underline and fill your code
                  index=________________________, # remove the underline and fill your code
                  columns=['English', 'Chinese', 'Math'])
print(df)

In [ ]:
# 1
marks = { 'Names': ['James', 'Andrew', 'Bob', 'Carlson'],
          'English': [58, 62, 77, 65],
          'Chinese': [55, 32, 64, 80],
          'Math': [61, 70, 81, 54]}

df = pd.DataFrame(marks)
df.set_index('Names', inplace=True)
print(df)

# 2
marks = {'James': [58, 55, 61],
         'Andrew': [62, 32, 70],
         'Bob': [77, 64, 81],
         'Carlson': [65, 80, 54]}

df = pd.DataFrame(marks.values(),
                  index=marks.keys(),
                  columns=['English', 'Chinese', 'Math'])
print(df)

In [ ]:
s = pd.Series( [ 1, 2, 1, 2, 1, 3])

In [ ]:
s = s.map({1: 1, 2: 3})

In [ ]:
s[5] = np.nan
s